/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citynursingh;
import BLL.BillCalculation;
import DB.PatientDB;
import java.util.List;

/**
 *
 * @author DTC
 */
public class ManagerSys extends javax.swing.JFrame {

    /**
     * Creates new form ManagerSys
     */
    public ManagerSys() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonViewBooking = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonAddPatient = new javax.swing.JButton();
        jTextFieldBill = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonNewCashier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButtonLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("City Nursing Home Hospital");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jButtonLogOut)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonLogOut))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Manager Dashboard");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("View Patient Booking Details");

        jButtonViewBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonViewBooking.setText("View");
        jButtonViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewBookingActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Add Patient Details");

        jButtonAddPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAddPatient.setText("Add");
        jButtonAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPatientActionPerformed(evt);
            }
        });

        jTextFieldBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBillActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Calculate Bill");

        jTextFieldSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Search Consultants");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("Create New User Account");

        jButtonNewCashier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNewCashier.setText("Create");
        jButtonNewCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashierActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("Enter Patient Name Here");

        jLabel9.setText("Enter Consultant ID/Name/Specialization");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)
                                    .addComponent(jTextFieldBill, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonViewBooking))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonAddPatient))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(jButtonNewCashier))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewBooking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonAddPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewCashier)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewBookingActionPerformed
        // TODO add your handling code here:
        PatientDB obj = new PatientDB();
        String patientDetails = obj.readPatientDetails();
        jTextArea1.setText(patientDetails);
    }//GEN-LAST:event_jButtonViewBookingActionPerformed

    private void jButtonAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPatientActionPerformed
        // TODO add your handling code here:
    javax.swing.JFrame addPatientFrame = new javax.swing.JFrame("Add Patient Details");
    addPatientFrame.setSize(400, 300);
    addPatientFrame.setLayout(new java.awt.GridLayout(6, 2));

    javax.swing.JLabel labelName = new javax.swing.JLabel("Name:");
    javax.swing.JTextField textName = new javax.swing.JTextField();

    javax.swing.JLabel labelAge = new javax.swing.JLabel("Age:");
    javax.swing.JTextField textAge = new javax.swing.JTextField();

    javax.swing.JLabel labelGender = new javax.swing.JLabel("Gender:");
    javax.swing.JTextField textGender = new javax.swing.JTextField();

    javax.swing.JLabel labelCategory = new javax.swing.JLabel("Category:");
    javax.swing.JTextField textCategory = new javax.swing.JTextField();

    javax.swing.JLabel labelContact = new javax.swing.JLabel("Contact:");
    javax.swing.JTextField textContact = new javax.swing.JTextField();

    javax.swing.JButton saveButton = new javax.swing.JButton("Save");

    addPatientFrame.add(labelName);
    addPatientFrame.add(textName);
    addPatientFrame.add(labelAge);
    addPatientFrame.add(textAge);
    addPatientFrame.add(labelGender);
    addPatientFrame.add(textGender);
    addPatientFrame.add(labelCategory);
    addPatientFrame.add(textCategory);
    addPatientFrame.add(labelContact);
    addPatientFrame.add(textContact);
    addPatientFrame.add(saveButton);

    addPatientFrame.setVisible(true);

    saveButton.addActionListener(e -> {
    String name = textName.getText().trim();
    String age = textAge.getText().trim();
    String gender = textGender.getText().trim();
    String category = textCategory.getText().trim();
    String contact = textContact.getText().trim();
    
     if (name.isEmpty() || age.isEmpty() || gender.isEmpty() || category.isEmpty() || contact.isEmpty()) {
        jTextArea1.setText("Error: All fields must be filled out.");
        return;
    }
        PatientDB db = new PatientDB();
         try {
            db.savePatientDetails(name, age, gender, category, contact);
            jTextArea1.setText("Patient details saved successfully!");
        } catch (Exception ex) {
            jTextArea1.setText("Error saving patient details.");
        }
        addPatientFrame.dispose(); 
    });  
   
    }//GEN-LAST:event_jButtonAddPatientActionPerformed

    private void jTextFieldBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBillActionPerformed
        // TODO add your handling code here:
        String patientName = jTextFieldBill.getText().trim();
     String category = PatientDB.getCategoryFromFile(patientName);
     
      if (category.isEmpty()) {
            jTextArea1.setText("Patient not found or invalid name.");
            return;
        }
       String billDetails = BillCalculation.calculateBill(category);
       jTextArea1.setText("Patient Name: "+patientName+" | "+billDetails);
    }//GEN-LAST:event_jTextFieldBillActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
         String searchTerm = jTextFieldSearch.getText().trim();
    if (searchTerm.isEmpty()) {
        jTextArea1.setText("Please enter a name or specialization to search.");
        return;
    }

    
    PatientDB db = new PatientDB();

  
    List<String> searchResults = db.searchConsultants(searchTerm);

 
    if (searchResults.isEmpty()) {
        jTextArea1.setText("No consultants found for the search term: " + searchTerm);
    } else {
        StringBuilder resultText = new StringBuilder("Search Results:\n");
        for (String result : searchResults) {
            resultText.append(result).append("\n");
        }
        jTextArea1.setText(resultText.toString());
    }
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        SystemHome logPage = new SystemHome();
        logPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonNewCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashierActionPerformed
        // TODO add your handling code here:
   javax.swing.JFrame addUserFrame = new javax.swing.JFrame("Add New User");
    addUserFrame.setSize(400, 300);
    addUserFrame.setLayout(new java.awt.GridLayout(4, 2));

    javax.swing.JLabel labelUsername = new javax.swing.JLabel("Username:");
    javax.swing.JTextField textUsername = new javax.swing.JTextField();

    javax.swing.JLabel labelPassword = new javax.swing.JLabel("Password:");
    javax.swing.JPasswordField textPassword = new javax.swing.JPasswordField();

   // javax.swing.JLabel labelRole = new javax.swing.JLabel("Role:");
   // javax.swing.JTextField textRole = new javax.swing.JTextField();
   javax.swing.JLabel labelRole = new javax.swing.JLabel("Role:");
   String[] roles = { "Cashier", "Consultant" };
   javax.swing.JComboBox<String> comboRole = new javax.swing.JComboBox<>(roles);

    javax.swing.JButton saveButton = new javax.swing.JButton("Save");

    addUserFrame.add(labelUsername);
    addUserFrame.add(textUsername);
    addUserFrame.add(labelPassword);
    addUserFrame.add(textPassword);
    addUserFrame.add(labelRole);
    addUserFrame.add(comboRole);
    addUserFrame.add(saveButton);

    addUserFrame.setVisible(true);

    // Add action listener to save button
    saveButton.addActionListener(e -> {
        String username = textUsername.getText().trim();
        String password = new String(textPassword.getPassword()).trim();
        String role = ((String) comboRole.getSelectedItem()).trim();

       // String role = comboRole.getText().trim();

        if (username.isEmpty() || password.isEmpty() || role.isEmpty()) {
            jTextArea1.setText("All fields must be filled out.");
            return;
        }

        // Call the method from UserManager to save details
        boolean isSaved = DB.AddUser.saveUserDetails(username, password, role);

        if (isSaved) {
             jTextArea1.setText("User details saved successfully!");
            addUserFrame.dispose();  // Close the frame after saving
        } else {
             jTextArea1.setText("Error saving user details.");
        }
         addUserFrame.dispose();
    });
        
    }//GEN-LAST:event_jButtonNewCashierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPatient;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonNewCashier;
    private javax.swing.JButton jButtonViewBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldBill;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
